FROM node:16-alpine

WORKDIR /app

# Make third party folders if needs
RUN mkdir -p /app/client

# Install third party libraries
# Install nano using apk
RUN apk update && \
    apk add --no-cache nano && \
    apk add --no-cache curl

WORKDIR /app/client

COPY package*.json ./

RUN npm install --force

# Copy the source code to the container
COPY . .

RUN cp .env.dev .env

# Command to start the development server using npm run dev
CMD [ "npm", "run", "dev" ]
