CREATE TABLE IF NOT EXISTS employees
(
    id BIGINT PRIMARY KEY,
    emplId BIGINT,
    projectId INT,
    dateFrom TIMESTAMPTZ,
    dateTo TIMESTAMPTZ,

    created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    edited TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted TIMESTAMPTZ NULL
);

CREATE SEQUENCE IF NOT EXISTS seq_employee_id START WITH 1000 INCREMENT BY 1;
